### PR TITLE
add jbang catalog so you can do jbang mima@maveniverse/mima

### PR DESCRIPTION
**Pull request by maxandersen**
the cli is nice - lets make it easy to get to :) 

this PR adds jbang-catalog.json in mima repo but would be better if maveniverse/jbang-catalog repo was created then we could just do `jbang mima@maveniverse`

### CODE REVIEW

**Comment by cstamas** [comment]
Created https://github.com/maveniverse/jbang-catalog

Is this PR still needed?

**Comment by cstamas** [comment]
Related JBang question https://github.com/jbangdev/jbang/issues/1734

**Comment by cstamas** [comment]
Created https://github.com/maveniverse/jbang-catalog and works just fine. Closing this issue.

**Comment by maxandersen** [comment]
Awesome and no - no more need for this pr

**Pull request closed without merging**
